<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
$questions = [

    /*
    |--------------------------------------------------------------------------
    | EASY LEVEL — 15 QUESTIONS
    |--------------------------------------------------------------------------
    */

    [
        'subject' => 'Hematology',
        'topic' => 'Complete Blood Count',
        'sub_topic' => 'Hemoglobin',
        'level' => 'easy',
        'question' => 'Which component of red blood cells is primarily responsible for transporting oxygen?',
        'option_a' => 'Fibrinogen',
        'option_b' => 'Hemoglobin',
        'option_c' => 'Albumin',
        'option_d' => 'Globulin',
        'correct_answer' => 'B',
        'explanation' => 'Hemoglobin binds oxygen in the lungs and transports it to body tissues.',
    ],
    [
        'subject' => 'Hematology',
        'topic' => 'White Blood Cells',
        'sub_topic' => 'Neutrophils',
        'level' => 'easy',
        'question' => 'Which white blood cell is usually the most numerous in normal adult peripheral blood?',
        'option_a' => 'Eosinophil',
        'option_b' => 'Basophil',
        'option_c' => 'Neutrophil',
        'option_d' => 'Monocyte',
        'correct_answer' => 'C',
        'explanation' => 'Neutrophils are normally the most abundant white blood cells in adult peripheral blood.',
    ],
    [
        'subject' => 'Hematology',
        'topic' => 'Coagulation',
        'sub_topic' => 'Platelets',
        'level' => 'easy',
        'question' => 'Which blood component is primarily involved in the initial formation of a platelet plug?',
        'option_a' => 'Red blood cells',
        'option_b' => 'Platelets',
        'option_c' => 'Lymphocytes',
        'option_d' => 'Albumin',
        'correct_answer' => 'B',
        'explanation' => 'Platelets adhere to damaged vessels and aggregate to form the initial platelet plug.',
    ],

    [
        'subject' => 'Clinical Chemistry',
        'topic' => 'Renal Function',
        'sub_topic' => 'Creatinine',
        'level' => 'easy',
        'question' => 'Which analyte is commonly used to evaluate kidney filtration?',
        'option_a' => 'Creatinine',
        'option_b' => 'Bilirubin',
        'option_c' => 'Amylase',
        'option_d' => 'Troponin',
        'correct_answer' => 'A',
        'explanation' => 'Serum creatinine is commonly used to estimate glomerular filtration and assess kidney function.',
    ],
    [
        'subject' => 'Clinical Chemistry',
        'topic' => 'Liver Function',
        'sub_topic' => 'Bilirubin',
        'level' => 'easy',
        'question' => 'An increased bilirubin concentration may cause which visible clinical finding?',
        'option_a' => 'Cyanosis',
        'option_b' => 'Jaundice',
        'option_c' => 'Pallor',
        'option_d' => 'Petechiae',
        'correct_answer' => 'B',
        'explanation' => 'Elevated bilirubin may cause yellow discoloration of the skin and sclera known as jaundice.',
    ],
    [
        'subject' => 'Clinical Chemistry',
        'topic' => 'Electrolytes',
        'sub_topic' => 'Sodium',
        'level' => 'easy',
        'question' => 'Which electrolyte is the major extracellular cation?',
        'option_a' => 'Potassium',
        'option_b' => 'Sodium',
        'option_c' => 'Magnesium',
        'option_d' => 'Phosphate',
        'correct_answer' => 'B',
        'explanation' => 'Sodium is the major cation in extracellular fluid.',
    ],

    [
        'subject' => 'Microbiology',
        'topic' => 'Bacteriology',
        'sub_topic' => 'Gram Stain',
        'level' => 'easy',
        'question' => 'Gram-positive bacteria normally appear what color after Gram staining?',
        'option_a' => 'Red',
        'option_b' => 'Purple',
        'option_c' => 'Green',
        'option_d' => 'Yellow',
        'correct_answer' => 'B',
        'explanation' => 'Gram-positive bacteria retain the crystal violet-iodine complex and appear purple.',
    ],
    [
        'subject' => 'Microbiology',
        'topic' => 'Mycology',
        'sub_topic' => 'Yeasts',
        'level' => 'easy',
        'question' => 'Which organism is commonly identified as a budding yeast?',
        'option_a' => 'Candida species',
        'option_b' => 'Escherichia coli',
        'option_c' => 'Staphylococcus aureus',
        'option_d' => 'Plasmodium species',
        'correct_answer' => 'A',
        'explanation' => 'Candida species commonly appear as budding yeast cells and may also form pseudohyphae.',
    ],
    [
        'subject' => 'Microbiology',
        'topic' => 'Parasitology',
        'sub_topic' => 'Malaria',
        'level' => 'easy',
        'question' => 'Which specimen is commonly examined to diagnose malaria?',
        'option_a' => 'Stool',
        'option_b' => 'Blood smear',
        'option_c' => 'Sputum',
        'option_d' => 'Cerebrospinal fluid',
        'correct_answer' => 'B',
        'explanation' => 'Thick and thin blood smears are commonly used to detect and identify malaria parasites.',
    ],

    [
        'subject' => 'Urinalysis',
        'topic' => 'Physical Examination',
        'sub_topic' => 'Urine Color',
        'level' => 'easy',
        'question' => 'What is the usual color of normal freshly voided urine?',
        'option_a' => 'Blue',
        'option_b' => 'Pale yellow to amber',
        'option_c' => 'Black',
        'option_d' => 'Milky white',
        'correct_answer' => 'B',
        'explanation' => 'Normal urine is usually pale yellow to amber because of the pigment urochrome.',
    ],
    [
        'subject' => 'Urinalysis',
        'topic' => 'Chemical Examination',
        'sub_topic' => 'Glucose',
        'level' => 'easy',
        'question' => 'Glucose in urine is most commonly associated with which condition?',
        'option_a' => 'Diabetes mellitus',
        'option_b' => 'Iron deficiency anemia',
        'option_c' => 'Hemophilia',
        'option_d' => 'Leukemia',
        'correct_answer' => 'A',
        'explanation' => 'Glucosuria commonly occurs when blood glucose exceeds the renal threshold, as in diabetes mellitus.',
    ],

    [
        'subject' => 'Blood Banking',
        'topic' => 'ABO Blood Group',
        'sub_topic' => 'Group A',
        'level' => 'easy',
        'question' => 'Which antigen is present on the red blood cells of a person with blood group A?',
        'option_a' => 'A antigen',
        'option_b' => 'B antigen',
        'option_c' => 'Both A and B antigens',
        'option_d' => 'Neither A nor B antigen',
        'correct_answer' => 'A',
        'explanation' => 'Group A red blood cells carry the A antigen.',
    ],
    [
        'subject' => 'Blood Banking',
        'topic' => 'Rh Blood Group',
        'sub_topic' => 'D Antigen',
        'level' => 'easy',
        'question' => 'A person is considered Rh positive when which antigen is present?',
        'option_a' => 'A antigen',
        'option_b' => 'B antigen',
        'option_c' => 'D antigen',
        'option_d' => 'H antigen',
        'correct_answer' => 'C',
        'explanation' => 'The presence of the D antigen generally determines Rh-positive status.',
    ],

    [
        'subject' => 'Immunology',
        'topic' => 'Immunoglobulins',
        'sub_topic' => 'IgG',
        'level' => 'easy',
        'question' => 'Which immunoglobulin is the most abundant in normal adult serum?',
        'option_a' => 'IgA',
        'option_b' => 'IgD',
        'option_c' => 'IgE',
        'option_d' => 'IgG',
        'correct_answer' => 'D',
        'explanation' => 'IgG is the most abundant immunoglobulin class in adult serum.',
    ],
    [
        'subject' => 'Immunology',
        'topic' => 'Immune Response',
        'sub_topic' => 'Antibodies',
        'level' => 'easy',
        'question' => 'Which cells differentiate into plasma cells that produce antibodies?',
        'option_a' => 'B lymphocytes',
        'option_b' => 'Neutrophils',
        'option_c' => 'Eosinophils',
        'option_d' => 'Platelets',
        'correct_answer' => 'A',
        'explanation' => 'Activated B lymphocytes differentiate into plasma cells that secrete antibodies.',
    ],

    /*
    |--------------------------------------------------------------------------
    | MEDIUM LEVEL — 15 QUESTIONS
    |--------------------------------------------------------------------------
    */

    [
        'subject' => 'Hematology',
        'topic' => 'Red Blood Cell Indices',
        'sub_topic' => 'MCV',
        'level' => 'medium',
        'question' => 'A patient has a mean corpuscular volume of 68 fL. How should the red blood cells be classified?',
        'option_a' => 'Macrocytic',
        'option_b' => 'Microcytic',
        'option_c' => 'Normocytic',
        'option_d' => 'Hyperchromic',
        'correct_answer' => 'B',
        'explanation' => 'An MCV below approximately 80 fL indicates microcytic red blood cells.',
    ],
    [
        'subject' => 'Hematology',
        'topic' => 'Anemias',
        'sub_topic' => 'Iron Deficiency',
        'level' => 'medium',
        'question' => 'Which laboratory pattern is most consistent with iron deficiency anemia?',
        'option_a' => 'High ferritin and low TIBC',
        'option_b' => 'Low ferritin and high TIBC',
        'option_c' => 'High serum iron and high ferritin',
        'option_d' => 'Normal ferritin and low transferrin',
        'correct_answer' => 'B',
        'explanation' => 'Iron deficiency anemia commonly produces low ferritin, low serum iron, and increased total iron-binding capacity.',
    ],
    [
        'subject' => 'Hematology',
        'topic' => 'Coagulation',
        'sub_topic' => 'Prothrombin Time',
        'level' => 'medium',
        'question' => 'The prothrombin time primarily evaluates which coagulation pathways?',
        'option_a' => 'Intrinsic and common pathways',
        'option_b' => 'Extrinsic and common pathways',
        'option_c' => 'Fibrinolytic pathway only',
        'option_d' => 'Platelet adhesion pathway only',
        'correct_answer' => 'B',
        'explanation' => 'PT evaluates the extrinsic and common coagulation pathways, including factors VII, X, V, II, and fibrinogen.',
    ],

    [
        'subject' => 'Clinical Chemistry',
        'topic' => 'Acid-Base Balance',
        'sub_topic' => 'Metabolic Acidosis',
        'level' => 'medium',
        'question' => 'Which arterial blood gas pattern is most consistent with primary metabolic acidosis?',
        'option_a' => 'High pH and high bicarbonate',
        'option_b' => 'Low pH and low bicarbonate',
        'option_c' => 'Low pH and high bicarbonate',
        'option_d' => 'High pH and high carbon dioxide',
        'correct_answer' => 'B',
        'explanation' => 'Primary metabolic acidosis is characterized by decreased pH and decreased bicarbonate.',
    ],
    [
        'subject' => 'Clinical Chemistry',
        'topic' => 'Liver Function',
        'sub_topic' => 'Cholestasis',
        'level' => 'medium',
        'question' => 'Which enzyme pattern is most suggestive of biliary obstruction?',
        'option_a' => 'Marked increase in alkaline phosphatase',
        'option_b' => 'Marked decrease in amylase',
        'option_c' => 'Marked increase in creatine kinase',
        'option_d' => 'Marked decrease in bilirubin',
        'correct_answer' => 'A',
        'explanation' => 'Alkaline phosphatase is commonly markedly increased in cholestasis and biliary obstruction.',
    ],
    [
        'subject' => 'Clinical Chemistry',
        'topic' => 'Cardiac Markers',
        'sub_topic' => 'Troponin',
        'level' => 'medium',
        'question' => 'Which marker is considered highly specific for myocardial injury?',
        'option_a' => 'Amylase',
        'option_b' => 'Cardiac troponin',
        'option_c' => 'Alkaline phosphatase',
        'option_d' => 'Alanine aminotransferase',
        'correct_answer' => 'B',
        'explanation' => 'Cardiac troponins are highly sensitive and specific markers of myocardial injury.',
    ],

    [
        'subject' => 'Microbiology',
        'topic' => 'Bacteriology',
        'sub_topic' => 'Catalase Test',
        'level' => 'medium',
        'question' => 'Which test is commonly used to differentiate Staphylococcus species from Streptococcus species?',
        'option_a' => 'Oxidase test',
        'option_b' => 'Catalase test',
        'option_c' => 'Indole test',
        'option_d' => 'Urease test',
        'correct_answer' => 'B',
        'explanation' => 'Staphylococcus species are catalase positive, while Streptococcus species are catalase negative.',
    ],
    [
        'subject' => 'Microbiology',
        'topic' => 'Bacteriology',
        'sub_topic' => 'Staphylococcus aureus',
        'level' => 'medium',
        'question' => 'Which test is commonly positive in Staphylococcus aureus and helps distinguish it from most other staphylococci?',
        'option_a' => 'Coagulase',
        'option_b' => 'Oxidase',
        'option_c' => 'Bile esculin',
        'option_d' => 'Optochin susceptibility',
        'correct_answer' => 'A',
        'explanation' => 'Staphylococcus aureus is characteristically coagulase positive.',
    ],
    [
        'subject' => 'Microbiology',
        'topic' => 'Mycology',
        'sub_topic' => 'Candida albicans',
        'level' => 'medium',
        'question' => 'Which rapid test is commonly used as a presumptive identification method for Candida albicans?',
        'option_a' => 'Germ tube test',
        'option_b' => 'Catalase test',
        'option_c' => 'Quellung reaction',
        'option_d' => 'Nagler reaction',
        'correct_answer' => 'A',
        'explanation' => 'Candida albicans commonly produces germ tubes when incubated in serum under appropriate conditions.',
    ],

    [
        'subject' => 'Urinalysis',
        'topic' => 'Microscopic Examination',
        'sub_topic' => 'Red Blood Cell Casts',
        'level' => 'medium',
        'question' => 'Red blood cell casts in urine are most strongly associated with which condition?',
        'option_a' => 'Glomerulonephritis',
        'option_b' => 'Lower urinary tract infection',
        'option_c' => 'Diabetes mellitus',
        'option_d' => 'Dehydration',
        'correct_answer' => 'A',
        'explanation' => 'Red blood cell casts indicate bleeding within the nephron and are strongly associated with glomerular disease.',
    ],
    [
        'subject' => 'Urinalysis',
        'topic' => 'Chemical Examination',
        'sub_topic' => 'Nitrite',
        'level' => 'medium',
        'question' => 'A positive urine nitrite test most commonly suggests the presence of which type of organism?',
        'option_a' => 'Nitrate-reducing bacteria',
        'option_b' => 'Yeast only',
        'option_c' => 'Viruses',
        'option_d' => 'Parasites',
        'correct_answer' => 'A',
        'explanation' => 'Many gram-negative urinary pathogens reduce nitrate to nitrite, producing a positive nitrite reaction.',
    ],

    [
        'subject' => 'Blood Banking',
        'topic' => 'Compatibility Testing',
        'sub_topic' => 'Major Crossmatch',
        'level' => 'medium',
        'question' => 'In a major crossmatch, the patient serum or plasma is tested against which component?',
        'option_a' => 'Patient red blood cells',
        'option_b' => 'Donor red blood cells',
        'option_c' => 'Donor platelets only',
        'option_d' => 'Patient white blood cells',
        'correct_answer' => 'B',
        'explanation' => 'A major crossmatch tests the patient serum or plasma against donor red blood cells.',
    ],
    [
        'subject' => 'Blood Banking',
        'topic' => 'Antiglobulin Testing',
        'sub_topic' => 'Direct Antiglobulin Test',
        'level' => 'medium',
        'question' => 'The direct antiglobulin test detects which condition?',
        'option_a' => 'Antibodies or complement attached to red blood cells in vivo',
        'option_b' => 'Free antibodies in patient serum only',
        'option_c' => 'Platelet aggregation',
        'option_d' => 'Fibrin degradation products',
        'correct_answer' => 'A',
        'explanation' => 'The direct antiglobulin test detects immunoglobulin or complement already coating red blood cells inside the body.',
    ],

    [
        'subject' => 'Immunology',
        'topic' => 'Complement',
        'sub_topic' => 'Classical Pathway',
        'level' => 'medium',
        'question' => 'The classical complement pathway is most commonly activated by which event?',
        'option_a' => 'Antigen-antibody complex formation',
        'option_b' => 'Direct bacterial endotoxin activation only',
        'option_c' => 'Platelet aggregation',
        'option_d' => 'Red blood cell production',
        'correct_answer' => 'A',
        'explanation' => 'The classical complement pathway is typically initiated when antibodies bind antigen.',
    ],
    [
        'subject' => 'Immunology',
        'topic' => 'Hypersensitivity',
        'sub_topic' => 'Type I',
        'level' => 'medium',
        'question' => 'Which immunoglobulin is primarily associated with type I immediate hypersensitivity reactions?',
        'option_a' => 'IgA',
        'option_b' => 'IgE',
        'option_c' => 'IgG',
        'option_d' => 'IgM',
        'correct_answer' => 'B',
        'explanation' => 'IgE binds mast cells and basophils and mediates immediate hypersensitivity reactions.',
    ],

    /*
    |--------------------------------------------------------------------------
    | HARD LEVEL — 15 QUESTIONS
    |--------------------------------------------------------------------------
    */

    [
        'subject' => 'Hematology',
        'topic' => 'Hemoglobinopathies',
        'sub_topic' => 'Sickle Cell Disease',
        'level' => 'hard',
        'question' => 'A patient has chronic hemolytic anemia, painful crises, and predominantly hemoglobin S on electrophoresis. Which diagnosis is most likely?',
        'option_a' => 'Iron deficiency anemia',
        'option_b' => 'Sickle cell disease',
        'option_c' => 'Hereditary spherocytosis',
        'option_d' => 'Aplastic anemia',
        'correct_answer' => 'B',
        'explanation' => 'Sickle cell disease is characterized by hemoglobin S, chronic hemolysis, and vaso-occlusive painful crises.',
    ],
    [
        'subject' => 'Hematology',
        'topic' => 'Coagulation Disorders',
        'sub_topic' => 'Hemophilia A',
        'level' => 'hard',
        'question' => 'A patient has a prolonged activated partial thromboplastin time, normal prothrombin time, and reduced factor VIII activity. Which disorder is most likely?',
        'option_a' => 'Hemophilia A',
        'option_b' => 'Vitamin K deficiency',
        'option_c' => 'Factor VII deficiency',
        'option_d' => 'Disseminated intravascular coagulation',
        'correct_answer' => 'A',
        'explanation' => 'Hemophilia A is caused by factor VIII deficiency and typically produces an isolated prolonged aPTT.',
    ],
    [
        'subject' => 'Hematology',
        'topic' => 'Leukemia',
        'sub_topic' => 'Acute Promyelocytic Leukemia',
        'level' => 'hard',
        'question' => 'Abnormal promyelocytes containing bundles of Auer rods are strongly associated with which leukemia?',
        'option_a' => 'Chronic lymphocytic leukemia',
        'option_b' => 'Acute promyelocytic leukemia',
        'option_c' => 'Chronic myeloid leukemia',
        'option_d' => 'Hairy cell leukemia',
        'correct_answer' => 'B',
        'explanation' => 'Acute promyelocytic leukemia commonly shows abnormal promyelocytes with multiple Auer rods and may be associated with DIC.',
    ],

    [
        'subject' => 'Clinical Chemistry',
        'topic' => 'Acid-Base Balance',
        'sub_topic' => 'Respiratory Compensation',
        'level' => 'hard',
        'question' => 'A patient has pH 7.28, bicarbonate 15 mmol/L, and decreased carbon dioxide. Which interpretation is most appropriate?',
        'option_a' => 'Metabolic acidosis with respiratory compensation',
        'option_b' => 'Respiratory acidosis with renal compensation',
        'option_c' => 'Metabolic alkalosis without compensation',
        'option_d' => 'Respiratory alkalosis without compensation',
        'correct_answer' => 'A',
        'explanation' => 'The low pH and low bicarbonate indicate metabolic acidosis, while decreased carbon dioxide reflects respiratory compensation.',
    ],
    [
        'subject' => 'Clinical Chemistry',
        'topic' => 'Endocrinology',
        'sub_topic' => 'Primary Hypothyroidism',
        'level' => 'hard',
        'question' => 'Which laboratory pattern is most consistent with primary hypothyroidism?',
        'option_a' => 'Low TSH and high free T4',
        'option_b' => 'High TSH and low free T4',
        'option_c' => 'Low TSH and low free T4 caused by thyroid failure',
        'option_d' => 'High TSH and high free T4',
        'correct_answer' => 'B',
        'explanation' => 'Primary thyroid failure produces low thyroid hormone levels and compensatory elevation of TSH.',
    ],
    [
        'subject' => 'Clinical Chemistry',
        'topic' => 'Protein Disorders',
        'sub_topic' => 'Monoclonal Gammopathy',
        'level' => 'hard',
        'question' => 'A narrow monoclonal spike in the gamma region on serum protein electrophoresis is most suggestive of which condition?',
        'option_a' => 'Acute inflammation',
        'option_b' => 'Multiple myeloma',
        'option_c' => 'Iron deficiency anemia',
        'option_d' => 'Nephrotic syndrome only',
        'correct_answer' => 'B',
        'explanation' => 'A narrow monoclonal protein spike may indicate a plasma cell disorder such as multiple myeloma.',
    ],

    [
        'subject' => 'Microbiology',
        'topic' => 'Bacteriology',
        'sub_topic' => 'Streptococcus pneumoniae',
        'level' => 'hard',
        'question' => 'An alpha-hemolytic, optochin-susceptible, bile-soluble gram-positive diplococcus is most likely which organism?',
        'option_a' => 'Streptococcus pyogenes',
        'option_b' => 'Streptococcus pneumoniae',
        'option_c' => 'Enterococcus faecalis',
        'option_d' => 'Staphylococcus epidermidis',
        'correct_answer' => 'B',
        'explanation' => 'Streptococcus pneumoniae is alpha-hemolytic, optochin susceptible, bile soluble, and appears as lancet-shaped diplococci.',
    ],
    [
        'subject' => 'Microbiology',
        'topic' => 'Enterobacterales',
        'sub_topic' => 'Escherichia coli',
        'level' => 'hard',
        'question' => 'A lactose-fermenting, indole-positive, oxidase-negative gram-negative rod isolated from urine is most likely which organism?',
        'option_a' => 'Escherichia coli',
        'option_b' => 'Pseudomonas aeruginosa',
        'option_c' => 'Salmonella enterica',
        'option_d' => 'Proteus mirabilis',
        'correct_answer' => 'A',
        'explanation' => 'Escherichia coli is a lactose-fermenting, indole-positive, oxidase-negative gram-negative rod and a common urinary pathogen.',
    ],
    [
        'subject' => 'Microbiology',
        'topic' => 'Anaerobic Bacteriology',
        'sub_topic' => 'Clostridium perfringens',
        'level' => 'hard',
        'question' => 'A gram-positive anaerobic bacillus showing a double zone of hemolysis is most suggestive of which organism?',
        'option_a' => 'Clostridium perfringens',
        'option_b' => 'Bacillus anthracis',
        'option_c' => 'Listeria monocytogenes',
        'option_d' => 'Corynebacterium diphtheriae',
        'correct_answer' => 'A',
        'explanation' => 'Clostridium perfringens characteristically produces a double zone of hemolysis on blood agar.',
    ],

    [
        'subject' => 'Urinalysis',
        'topic' => 'Microscopic Examination',
        'sub_topic' => 'Casts',
        'level' => 'hard',
        'question' => 'Broad waxy casts are most commonly associated with which condition?',
        'option_a' => 'Advanced chronic renal disease',
        'option_b' => 'Lower urinary tract infection',
        'option_c' => 'Transient dehydration only',
        'option_d' => 'Uncomplicated cystitis',
        'correct_answer' => 'A',
        'explanation' => 'Broad waxy casts form in dilated, damaged tubules and are associated with advanced chronic renal disease.',
    ],
    [
        'subject' => 'Urinalysis',
        'topic' => 'Chemical Examination',
        'sub_topic' => 'Blood Reaction',
        'level' => 'hard',
        'question' => 'A urine reagent strip is strongly positive for blood, but no red blood cells are seen microscopically. Which substance may explain the result?',
        'option_a' => 'Myoglobin',
        'option_b' => 'Glucose',
        'option_c' => 'Bilirubin',
        'option_d' => 'Ketones',
        'correct_answer' => 'A',
        'explanation' => 'The blood pad detects heme activity and may react with free hemoglobin or myoglobin even when intact red blood cells are absent.',
    ],

    [
        'subject' => 'Blood Banking',
        'topic' => 'Antibody Identification',
        'sub_topic' => 'Rh Antibodies',
        'level' => 'hard',
        'question' => 'A patient antibody reacts at the antiglobulin phase, is enhanced by enzymes, and does not react with D-negative cells. Which specificity is most likely?',
        'option_a' => 'Anti-D',
        'option_b' => 'Anti-M',
        'option_c' => 'Anti-Lea',
        'option_d' => 'Anti-P1',
        'correct_answer' => 'A',
        'explanation' => 'Anti-D reacts with D-positive cells, is typically detected at the antiglobulin phase, and may be enhanced by enzyme treatment.',
    ],
    [
        'subject' => 'Blood Banking',
        'topic' => 'Hemolytic Disease',
        'sub_topic' => 'Rh Immune Globulin',
        'level' => 'hard',
        'question' => 'What is the primary purpose of administering Rh immune globulin to an eligible Rh-negative mother?',
        'option_a' => 'Treat maternal anemia',
        'option_b' => 'Prevent maternal sensitization to the D antigen',
        'option_c' => 'Increase fetal platelet production',
        'option_d' => 'Remove maternal anti-A antibodies',
        'correct_answer' => 'B',
        'explanation' => 'Rh immune globulin prevents the Rh-negative mother from becoming immunized against fetal D-positive red blood cells.',
    ],

    [
        'subject' => 'Immunology',
        'topic' => 'Autoimmunity',
        'sub_topic' => 'Systemic Lupus Erythematosus',
        'level' => 'hard',
        'question' => 'Which autoantibody is highly specific for systemic lupus erythematosus?',
        'option_a' => 'Anti-double-stranded DNA',
        'option_b' => 'Rheumatoid factor',
        'option_c' => 'Anti-mitochondrial antibody',
        'option_d' => 'Anti-centromere antibody',
        'correct_answer' => 'A',
        'explanation' => 'Anti-double-stranded DNA antibodies are strongly associated with systemic lupus erythematosus and may correlate with renal disease activity.',
    ],
    [
        'subject' => 'Immunology',
        'topic' => 'Immunodeficiency',
        'sub_topic' => 'HIV',
        'level' => 'hard',
        'question' => 'Which lymphocyte population is progressively reduced in untreated HIV infection?',
        'option_a' => 'CD4-positive T lymphocytes',
        'option_b' => 'CD8-positive T lymphocytes only',
        'option_c' => 'B lymphocytes only',
        'option_d' => 'Natural killer cells only',
        'correct_answer' => 'A',
        'explanation' => 'HIV primarily infects and progressively reduces CD4-positive helper T lymphocytes.',
    ],
];

        foreach ($questions as $question) {
            Question::updateOrCreate(
                ['question' => $question['question']],
                $question
            );
        }
    }
}
